import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Fotter } from '../components/Fotter/Fotter'
import {Main} from '../components/Main/Main'
import { Header } from '../components/Header/Header'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header></Header>
      <Main page="about"/>
      <Fotter/>
    </div>
  )
}