import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Fotter } from '../components/Fotter/Fotter'
import { Main } from '../components/Main/Main'
import { Header } from '../components/Header/Header'
import { useState,useCallback,useEffect } from 'react'

export default function Home() {
  const [foo, setFoo] = useState(1);
  const [count,setCount] = useState(40)
  const handleClick = useCallback(() =>{
    if(foo < 20){
      setFoo(foo=>foo+1);
    }
  },[foo])

  useEffect(()=>{
    return()=>{
      console.log(count);
    }
  },[foo,count])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header></Header>
      <h1>{foo}</h1>
      <button onClick={handleClick}>ボタンですよ</button>
      <Main page="index"/>
      <Fotter/>
    </div>
  )
}
