import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Fotter } from '../components/Fotter'
import { Links } from '../components/Links'
import { Headline } from '../components/Headline'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Headline title="about"/>
        <Links/>
      </main>

      <Fotter/>
    </div>
  )
}